---
  - src: https://github.com/netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elastic 
  - src: https://github.com/dotsenkois/kibana-role.git
    scm: git
    version: "1.0.1"
    name: kibana 
  - src: https://github.com/dotsenkois/filebeat-role.git
    scm: git
    version: "1.0.1"
    name: filebeat 
  - src: https://github.com/dotsenkois/logstash-role.git
    scm: git
    version: "1.0.1"
    name: logstash 
