---
  - src: https://github.com/netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elastic 
  - src: https://github.com/dotsenkois/kibana_role.git
    scm: git
    version: "latest"
    name: kibana_role 
  - src: https://github.com/dotsenkois/filebeat_role.git
    scm: git
    version: "latest"
    name: filebeat_role 
  - src: https://github.com/dotsenkois/logstash_role.git
    scm: git
    version: "latest"
    name: logstash_role 