all:
  vars:
    ansible_connection: ssh
    ansible_user: dotsenkois
app:
  hosts:
    app-node01:
      ansible_host: 10.130.0.20
    app-node02:
      ansible_host: 10.130.0.21
kibana:
  hosts:
    kib-node01:
      ansible_host: 10.130.0.11
elasticsearch:
  hosts:
    es-node01:
      ansible_host: 10.130.0.10
